#!/usr/bin/env python3
"""Reconcile Jellyfin library-update notifications into Radarr, Sonarr and Bazarr.

Jellyfin lives on orthanc and its media arrives over NFS from erebor, written by
containers on pirateship. Its real-time monitor therefore never fires (inotify
does not see writes made by a different NFS client), so without an explicit push
the library only updates on the scheduled scan and keeps serving paths for files
that have already been replaced by an upgrade.

This declares that push. Desired state comes from a JSON spec generated by Nix;
the running instances are reconciled to it. Idempotent.

Library IDs are discovered from Jellyfin at runtime rather than pinned in Nix,
so recreating a library does not silently break the mapping.
"""
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

SPEC = sys.argv[1]
JELLYFIN_KEY_FILE = sys.argv[2]

# Literal IP, not `rivendell`: a push that says "your media wiring is broken"
# should not itself depend on name resolution. Same address the other modules use.
NTFY_URL = "http://10.0.1.9:2586/homelab"


def jf_auth(key):
    """Auth header for Jellyfin's own API.

    Jellyfin 12.0 set EnableLegacyAuthorization=false, which removed
    X-Emby-Token, X-MediaBrowser-Token and ?api_key=. This script used
    X-Emby-Token, so every call started returning 401 the morning orthanc
    upgraded to 12.0.0 (2026-09-15 04:02) — with a key that was never invalid.
    Verified against the live server: the same key returns 401 with
    X-Emby-Token and 200 with the header below, on every endpoint tried.

    `Authorization: MediaBrowser Token="..."` is not new in 12.0 — it is the
    long-standing form for a static API key and works on older servers too, so
    this needs no version branching.
    """
    return {"Authorization": 'MediaBrowser Token="%s"' % key}

with open(SPEC) as fh:
    spec = json.load(fh)
with open(JELLYFIN_KEY_FILE) as fh:
    JF_KEY = fh.read().strip()

JF = spec["jellyfin"]
JF_BASE = "http%s://%s:%d" % ("s" if JF["useSsl"] else "", JF["host"], JF["port"])
changed = []


def http(url, method="GET", headers=None, data=None, timeout=30):
    req = urllib.request.Request(url, method=method, data=data, headers=headers or {})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        raw = r.read()
    return json.loads(raw) if raw and raw[:1] in b"[{" else raw


def wait_for(url, headers, label, attempts=60):
    for _ in range(attempts):
        try:
            http(url, headers=headers, timeout=10)
            return True
        except (urllib.error.URLError, TimeoutError, ConnectionError, OSError):
            time.sleep(2)
    return False


def notify(title, body, priority="4", tags="warning"):
    try:
        req = urllib.request.Request(
            NTFY_URL, data=body.encode(),
            headers={"Title": title, "Priority": priority, "Tags": tags})
        with urllib.request.urlopen(req, timeout=15) as r:
            r.read()
    except Exception:
        pass


def degrade(reason):
    """Report a Jellyfin-side failure and exit SUCCESSFULLY.

    This script reconciles configuration inside OTHER applications. Whether
    Jellyfin — on a different host, upgraded on its own schedule — is answering
    right now must not decide whether a NixOS activation succeeds.

    It used to. `switch-to-configuration` exits non-zero if any unit fails to
    start, so a 401 from Jellyfin failed the whole switch: deploy-rs rolled the
    host back, and the nightly upgrade reported FAILED. On 2026-09-15 an
    unattended Jellyfin 12.0 upgrade on orthanc did exactly that to pirateship.
    The same shape hit music-library-audit on Sep 9-10 (see #676).

    Exiting 0 here is deliberate and is NOT silent: the reason goes to the
    journal and to ntfy, so a skipped reconcile is visible without being able to
    take the host down with it. The timer retries hourly, so a transient
    Jellyfin outage heals itself with no deploy involved.
    """
    sys.stderr.write("jellyfin unavailable, skipping reconcile: %s\n" % reason)
    notify(
        "Jellyfin notify sync skipped",
        "pirateship: could not reconcile Jellyfin library-update notifications.\n\n"
        "%s\n\n"
        "Radarr/Sonarr/Bazarr were left as they are. Library updates may not be\n"
        "pushed to Jellyfin until this is resolved. Retrying hourly.\n\n"
        "  journalctl -u jellyfin-notify-sync -n 50" % reason)
    sys.exit(0)


# ---------------------------------------------------------------- jellyfin
if not wait_for(JF_BASE + "/System/Info/Public", {}, "jellyfin"):
    degrade("%s did not become reachable" % JF_BASE)

try:
    folders = http(JF_BASE + "/Library/VirtualFolders", headers=jf_auth(JF_KEY))
except urllib.error.HTTPError as e:
    if e.code in (401, 403):
        degrade("Jellyfin rejected the API key (HTTP %d). Jellyfin 12.0 removed "
                "the legacy X-Emby-Token/?api_key= auth; if this appeared after a "
                "Jellyfin upgrade, check the key in sops is still valid." % e.code)
    degrade("Jellyfin returned HTTP %d for /Library/VirtualFolders" % e.code)
except (urllib.error.URLError, TimeoutError, ConnectionError, OSError) as e:
    degrade("Jellyfin unreachable during library discovery: %s" % e)

libs = {}
for v in folders:
    ct = v.get("CollectionType")
    if ct in ("movies", "tvshows"):
        libs[ct] = {"id": v.get("ItemId"), "name": v.get("Name")}
for want in ("movies", "tvshows"):
    if want not in libs:
        degrade("jellyfin has no %r library; found %s"
                % (want, [v.get("CollectionType") for v in folders]))


# ------------------------------------------------------------ radarr/sonarr
def sync_arr(app):
    base = "http://localhost:%d/api/v3" % app["port"]
    with open(app["keyFile"]) as fh:
        key = fh.read().strip()
    hdr = {"X-Api-Key": key, "Content-Type": "application/json"}
    wait_for(base + "/system/status", hdr, app["app"])

    schema = http(base + "/notification/schema", headers=hdr)
    proto = next((s for s in schema if s.get("implementation") == "MediaBrowser"), None)
    if proto is None:
        sys.exit("%s: no MediaBrowser notification implementation" % app["app"])

    want_fields = {
        "host": JF["host"], "port": JF["port"], "useSsl": JF["useSsl"],
        "apiKey": JF_KEY, "notify": False, "updateLibrary": True,
        # Radarr/Sonarr run in gluetun's netns with /var/lib/media bind-mounted
        # at /media, so the paths they know are not the paths Jellyfin knows.
        # Without this translation Jellyfin cannot match the reported path to a
        # library item and the targeted refresh silently does nothing.
        "mapFrom": app["mapFrom"], "mapTo": app["mapTo"],
    }

    body = json.loads(json.dumps(proto))   # clone the schema as the template
    body["name"] = app["notificationName"]
    body["tags"] = []
    for f in body.get("fields") or []:
        if f["name"] in want_fields:
            f["value"] = want_fields[f["name"]]
    for k in list(body.keys()):
        if k.startswith("on") and isinstance(body[k], bool):
            body[k] = k in app["triggers"]

    existing = http(base + "/notification", headers=hdr)
    cur = next((n for n in existing if n.get("name") == app["notificationName"]), None)

    def field_map(n):
        return {f["name"]: f.get("value") for f in n.get("fields") or []}

    if cur is None:
        http(base + "/notification", "POST", hdr, json.dumps(body).encode())
        changed.append("%-7s created notification %r" % (app["app"], body["name"]))
        return

    cm, wm = field_map(cur), field_map(body)
    # Radarr and Sonarr return secret fields as '********' on read, so a naive
    # comparison against the real value always reports drift and rewrites the
    # notification on every run. Treat the mask as "opaque, assume unchanged".
    #
    # Consequence: rotating jellyfin_api_key is NOT picked up automatically —
    # delete the notification (or change any other field) to force a rewrite.
    # Do not "fix" this by testing the connection instead: POST /notification/test
    # returns 200 even with a deliberately wrong API key, because the arr does
    # not check Jellyfin's response. It proves reachability, nothing more.
    drift = [k for k, v in wm.items()
             if cm.get(k) != v and cm.get(k) != "********"]
    trig = [k for k in body if k.startswith("on") and isinstance(body[k], bool)
            and cur.get(k) != body[k]]
    if drift or trig:
        body["id"] = cur["id"]
        http(base + "/notification/%d" % cur["id"], "PUT", hdr, json.dumps(body).encode())
        detail = ", ".join(sorted(set([d for d in drift if d != "apiKey"] + trig))) or "apiKey"
        changed.append("%-7s updated notification (%s)" % (app["app"], detail))


for a in spec["arr"]:
    sync_arr(a)


# ---------------------------------------------------------------- bazarr
bz = spec.get("bazarr")
if bz:
    # Bazarr generates its own API key and rewrites config.yaml at runtime, so
    # read it from there rather than pinning a copy in sops.
    with open(bz["configPath"]) as fh:
        cfg_txt = fh.read()
    bkey = re.search(r"^auth:\s*$\s*apikey:\s*(\S+)", cfg_txt, re.M).group(1)
    bbase = "http://localhost:%d" % bz["port"]
    bhdr = {"X-API-KEY": bkey}
    wait_for(bbase + "/api/system/settings", bhdr, "bazarr")

    cur = http(bbase + "/api/system/settings", headers=bhdr)
    cj, cg = cur.get("jellyfin") or {}, cur.get("general") or {}

    scalars = {
        "general-use_jellyfin": True,
        "jellyfin-url": JF_BASE,
        "jellyfin-apikey": JF_KEY,
        "jellyfin-update_movie_library": True,
        "jellyfin-update_series_library": True,
        "jellyfin-refresh_method": bz["refreshMethod"],
    }
    lists = {
        "jellyfin-movie_library": [libs["movies"]["name"]],
        "jellyfin-movie_library_ids": [libs["movies"]["id"]],
        "jellyfin-series_library": [libs["tvshows"]["name"]],
        "jellyfin-series_library_ids": [libs["tvshows"]["id"]],
    }

    def current(dotted):
        sect, k = dotted.split("-", 1)
        return (cg if sect == "general" else cj).get(k)

    drift = [k for k, v in scalars.items() if current(k) != v]
    drift += [k for k, v in lists.items() if current(k) != v]

    if drift:
        # Lists MUST be repeated form keys. A JSON-encoded string is accepted
        # with HTTP 204 but stores a one-element list holding the JSON text.
        pairs = [("settings-" + k, "true" if v is True else "false" if v is False else v)
                 for k, v in scalars.items()]
        for k, v in lists.items():
            for item in v:
                pairs.append(("settings-" + k, item))
        http(bbase + "/api/system/settings", "POST", bhdr,
             urllib.parse.urlencode(pairs).encode())

        # Bazarr answers 204 regardless, so confirm the values actually landed.
        time.sleep(2)
        after = http(bbase + "/api/system/settings", headers=bhdr)
        aj, ag = after.get("jellyfin") or {}, after.get("general") or {}

        def now(dotted):
            sect, k = dotted.split("-", 1)
            return (ag if sect == "general" else aj).get(k)

        bad = [k for k, v in list(scalars.items()) + list(lists.items()) if now(k) != v]
        bad = [k for k in bad if k != "jellyfin-apikey"]  # not echoed back verbatim
        if bad:
            sys.exit("bazarr: settings did not persist: %s" % bad)
        changed.append("bazarr  updated jellyfin settings (%s)"
                       % ", ".join(sorted(k for k in drift if k != "jellyfin-apikey")))

print("\n".join(changed) if changed else "up to date")
