# modules/lidarr-formats.nix — declarative custom formats for Lidarr
#
# Lidarr is the one arr app with no declarative sync path. TRaSH Guides has no
# Lidarr content at all ("TRaSH Guides do not have any guides related to
# Lidarr"), and Recyclarr supports "Radarr and Sonarr (v4 and higher only)".
# The closest thing is Davo's community guide, now folded into the Servarr wiki
# Lidarr tips-and-tricks page — a set of hand-written examples, not a synced
# data source.
#
# So this module plays the role recyclarr plays in arr-stack.nix: the desired
# state lives here in Nix, and a small oneshot reconciles the running instance
# to it over the API. Without this the formats are UI-only state that lives in
# lidarr.db and vanishes if the config volume is ever rebuilt.
#
# Lidarr's custom format engine is far weaker than Radarr's or Sonarr's. It
# exposes exactly four specification types — ReleaseTitle, ReleaseGroup,
# IndexerFlag and Size — with no source, resolution or language specs. Every
# decision therefore has to be made by regex against the release title, and
# Lidarr's profile schema has no minUpgradeFormatScore, so the anti-churn lever
# used for radarr/sonarr does not exist here.
#
# Scoring targets Redacted, which supplies nearly all grabs and emits highly
# structured titles via Prowlarr:
#
#   Dr. Dre - 2001 (1999) [Album] [FLAC Lossless / CD / Log (100%) / Cue]
#   Ferry Corsten & Gouryella - Neba (2016) [Single] [FLAC Lossless / WEB]
#
# "Log (100%)" is RED's verified-perfect-rip marker and is the single most
# useful signal in the title. Log Present and Perfect Log stack deliberately so
# the ordering comes out perfect log > imperfect log > no log; a lone "imperfect
# log" penalty would have ranked a 95% log *below* a rip with no log at all,
# which is backwards. Verified against real titles:
#
#   75  [FLAC Lossless / CD / Log (100%) / Cue]   perfect rip
#   35  [FLAC Lossless / CD / Log (95%) / Cue]    logged, imperfect
#   25  [FLAC Lossless / CD / Cue]                unlogged
#   20  [FLAC Lossless / CD]
#   10  [FLAC Lossless / WEB]
#    0  Artist.Album.2020.FLAC-GROUP              unstructured (usenet)
#  -10000 [FLAC 24bit Lossless / Vinyl]
#
# There is deliberately no "Lossless" format: the Lossless quality profile only
# admits FLAC/ALAC/APE/WavPack, so every release that reaches scoring is already
# lossless and the format would score every candidate equally.
#
# minFormatScore stays 0 rather than the guide's suggested 1. NZBgeek titles
# carry no media tag and score 0 (see the table above), so a floor of 1 would
# reject every usenet result outright. Scoring here is for *sorting* the
# interactive search list, not for gating — grabs are all manual.
#
# 24bit is scored 0: it tags hi-res for visibility without expressing a
# preference. Set it negative to favour 16-bit CD rips on size, or positive to
# chase hi-res.

{ config, pkgs, lib, ... }:

let
  spec = pkgs.writeText "lidarr-formats.json" (builtins.toJSON {
    # Quality profile these scores are applied to. Must already exist.
    profile = "Lossless";
    minFormatScore = 0;
    formats = [
      { name = "Perfect Log";       score =     40; regex = "Log \\(100%\\)"; }
      { name = "CD Source";         score =     20; regex = "\\bCD\\b"; }
      { name = "Log Present";       score =     10; regex = "\\bLog\\b"; }
      { name = "WEB Source";        score =     10; regex = "\\bWEB\\b"; }
      { name = "Cue Sheet";         score =      5; regex = "\\bCue\\b"; }
      { name = "24bit";             score =      0; regex = "\\b24bit\\b"; }
      { name = "Inferior Transfer"; score = -10000; regex = "\\b(Vinyl|Cassette|Soundboard)\\b"; }
    ];
  });
in
{
  systemd.services.lidarr-format-sync = {
    description = "Sync declared custom formats into Lidarr";
    after = [ "podman-lidarr.service" ];
    wants = [ "podman-lidarr.service" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # Retry rather than give up: on a cold boot the container is up well
      # before the API binds, and the script's own wait loop only covers 120s.
      Restart = "on-failure";
      RestartSec = "60s";
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.python3}/bin/python3"
        "${./lidarr-format-sync.py}"
        "${spec}"
        # The API key is read from Lidarr's own config at runtime rather than
        # kept in sops: it is generated by Lidarr, changes if the config volume
        # is reset, and is already on disk here. Nothing secret is added to the
        # nix store this way.
        "/var/lib/lidarr/config/config.xml"
      ];
    };
  };

  homelab.postUpgradeCheck.services = [ "lidarr-format-sync" ];
}
