keys:
  - &pirateship age1pxxlxkd648efrgfdr5r3yfxnv5zmqqp57k7yrc06h7x3r367eqcqdel4uy
  - &liquidark age1tl6nxc9gl080x7vxy8l9mc5eps0sp33rwdlylt2uvhkuy6l6hvsqmcx0av

creation_rules:
  - path_regex: secrets/pirateship.yaml$
    key_groups:
      - age:
        - *pirateship
        - *liquidark
